SOURCES = \
    feynplot/cli/feyncli.py \
    feynplot/cli/__init__.py \
    feynplot/core/bezier.py \
    feynplot/core/circle.py \
    feynplot/core/diagram.py \
    feynplot/core/extra_text_element.py \
    feynplot/core/fermion_methods.py \
    feynplot/core/FeynmanDiagramExtended.py \
    feynplot/core/gluon_methods.py \
    feynplot/core/line.py \
    feynplot/core/particle.py \
    feynplot/core/photon_methods.py \
    feynplot/core/special_curves.py \
    feynplot/core/style.py \
    feynplot/core/vertex.py \
    feynplot/core/WZ_methods.py \
    feynplot/core/__init__.py \
    feynplot/default_settings/default_settings.py \
    feynplot/default_settings/__init__.py \
    feynplot/drawing/fontSettings.py \
    feynplot/drawing/plot_functions.py \
    feynplot/drawing/renderer.py \
    feynplot/drawing/styles/arrow_styles.py \
    feynplot/drawing/styles/line_styles.py \
    feynplot/drawing/styles/vertex_styles.py \
    feynplot/drawing/styles/__init__.py \
    feynplot/drawing/__init__.py \
    feynplot/io/diagram_io.py \
    feynplot/io/diagram_io_test.py \
    feynplot/io/__init__.py \
    feynplot/shared/common_functions.py \
    feynplot/tests/test_oval_generation.py \
    feynplot/tests/__init__.py \
    feynplot/utils/geometry.py \
    feynplot/utils/__init__.py \
    feynplot/__init__.py \
    feynplot_gui/core_ui/controllers/canvas_controller.py \
    feynplot_gui/core_ui/controllers/line_controller.py \
    feynplot_gui/core_ui/controllers/line_dialogs/edit_line.py \
    feynplot_gui/core_ui/controllers/line_dialogs/edit_loop.py \
    feynplot_gui/core_ui/controllers/line_dialogs/edit_loop_dialog.py \
    feynplot_gui/core_ui/controllers/line_dialogs/line_edit_base.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_linestyle_editors/hollow_line_editor.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_line_editors/fermion_line_editor.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_line_editors/gluon_line_editor.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_line_editors/loop_editors.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_line_editors/photon_line_editor.py \
    feynplot_gui/core_ui/controllers/line_dialogs/specific_line_editors/wz_boson_line_editor.py \
    feynplot_gui/core_ui/controllers/line_dialogs/__init__.py \
    feynplot_gui/core_ui/controllers/main_controller.py \
    feynplot_gui/core_ui/controllers/navigation_bar_controller.py \
    feynplot_gui/core_ui/controllers/other_texts_controller.py \
    feynplot_gui/core_ui/controllers/other_texts_dialogs/edit_text_dialog.py \
    feynplot_gui/core_ui/controllers/other_texts_dialogs/__init__.py \
    feynplot_gui/core_ui/controllers/toolbox_controller.py \
    feynplot_gui/core_ui/controllers/vertex_controller.py \
    feynplot_gui/core_ui/controllers/vertex_dialogs/edit_vertex.py \
    feynplot_gui/core_ui/controllers/vertex_dialogs/search_properties.py \
    feynplot_gui/core_ui/controllers/vertex_dialogs/__init__.py \
    feynplot_gui/core_ui/controllers/__init__.py \
    feynplot_gui/core_ui/debug_utils.py \
    feynplot_gui/core_ui/dialogs/add_line_dialog.py \
    feynplot_gui/core_ui/dialogs/add_vertex_dialog.py \
    feynplot_gui/core_ui/dialogs/delete_line_dialog.py \
    feynplot_gui/core_ui/dialogs/delete_vertex_dialog.py \
    feynplot_gui/core_ui/dialogs/line_dialogs/edit_all_lines_dialog.py \
    feynplot_gui/core_ui/dialogs/line_dialogs/__init__.py \
    feynplot_gui/core_ui/dialogs/matplotlib_settings_dialog.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/matplotlib_settings_dialog.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_axes_ticks_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_collapsible_group_box.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_figure_save_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_font_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_latex_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_legend_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/_lines_markers_settings_panel.py \
    feynplot_gui/core_ui/dialogs/plt_dialogs/__init__.py \
    feynplot_gui/core_ui/dialogs/vertex_dialogs/edit_all_vertices_dialog.py \
    feynplot_gui/core_ui/dialogs/vertex_dialogs/__init__.py \
    feynplot_gui/core_ui/dialogs/__init__.py \
    feynplot_gui/core_ui/mouse_event_handler.py \
    feynplot_gui/core_ui/selection_highlighter.py \
    feynplot_gui/core_ui/test_locale.py \
    feynplot_gui/core_ui/widgets/canvas_widget.py \
    feynplot_gui/core_ui/widgets/line_list_widget.py \
    feynplot_gui/core_ui/widgets/main_window.py \
    feynplot_gui/core_ui/widgets/navigation_bar_widget.py \
    feynplot_gui/core_ui/widgets/other_texts_widget.py \
    feynplot_gui/core_ui/widgets/toolbox_widget.py \
    feynplot_gui/core_ui/widgets/vertex_list_widget.py \
    feynplot_gui/core_ui/widgets/__init__.py \
    feynplot_gui/core_ui/__init__.py \
    feynplot_gui/core_ui/__main__.py \
    feynplot_gui/debug/debug_output.py \
    feynplot_gui/debug/find_caller.py \
    feynplot_gui/debug_utils.py \
    feynplot_gui/default/default_settings.py \
    feynplot_gui/default/__init__.py \
    feynplot_gui/find_strs.py \
    feynplot_gui/shared/shared.py \
    feynplot_gui/test/test_annotate.py \
    feynplot_gui/test/test_bkg.py \
    feynplot_gui/test/test_brace.py \
    feynplot_gui/test/test_clip.py \
    feynplot_gui/test/test_curve.py \
    feynplot_gui/test/test_curve_2.py \
    feynplot_gui/test/test_fix_font_to_grid.py \
    feynplot_gui/test/test_generate_point.py \
    feynplot_gui/test/test_get_text_range2.py \
    feynplot_gui/test/test_get_text_range3.py \
    feynplot_gui/test/test_get_text_ranges.py \
    feynplot_gui/test/test_grid.py \
    feynplot_gui/test/test_QTimer.py \
    feynplot_gui/test/test_renderer.py \
    feynplot_gui/test/test_style.py \
    feynplot_gui/__init__.py \
    feynplot_gui/__main__.py \
